import crypto from 'crypto';
import { getChallenge, deleteChallenge } from './pow-store';

/**
 * Verifies a Proof of Work (PoW) challenge solution.
 * 
 * 1. Checks if the challenge exists in the store and hasn't expired.
 * 2. Natively hashes the challenge and nonce using SHA-256.
 *    Supports both `${challengeString}:${nonce}` and `${challengeString}${nonce}` for flexibility.
 * 3. Verifies that the hash starts with the required number of zeros (difficulty).
 * 4. CRITICAL: If valid, instantly deletes the challenge from the store to prevent Replay Attacks.
 * 
 * @param challengeString The challenge string generated by the server
 * @param nonce The numerical nonce solved by the client
 * @returns boolean indicating if the solution is valid
 */
export function verifyPoW(challengeString: string, nonce: number): boolean {
  if (!challengeString || typeof nonce !== 'number' || isNaN(nonce)) {
    return false;
  }

  // 1. Retrieve challenge from store. This also handles lazy expiration check/deletion.
  const challenge = getChallenge(challengeString);
  if (!challenge) {
    return false;
  }

  // 2. Generate SHA-256 hash using native Node.js crypto module.
  // We test both with-colon and without-colon patterns to align with any frontend implementation.
  const inputWithColon = `${challengeString}:${nonce}`;
  const inputWithoutColon = `${challengeString}${nonce}`;

  const hashWithColon = crypto.createHash('sha256').update(inputWithColon).digest('hex');
  const hashWithoutColon = crypto.createHash('sha256').update(inputWithoutColon).digest('hex');

  const expectedPrefix = '0'.repeat(challenge.difficulty);

  // 3. Verify prefix requirements
  const isValid = hashWithColon.startsWith(expectedPrefix) || hashWithoutColon.startsWith(expectedPrefix);

  // 4. CRITICAL: Prevent Replay Attacks by instantly deleting the challenge upon successful verification.
  if (isValid) {
    deleteChallenge(challengeString);
  }

  return isValid;
}
